### ISSUE TITLE
[iOS] Tags appear clipped in some views

### ISSUE THREAD

**Issue by michalcs** [anyboxhq/bug-reports-anybox#1]
```
iPhone 14 Pro
iOS 17.1
Anybox 2.1.2 (190)
```
## Steps 

1. save a new link to `Today` view (or any view where there's only one? item)
2. open the Tags sheet and assign a tag
3. close the Tags sheet by tapping the `(x)` button
4. observe the tag appearance 

## Expected

The tag should be fully visible

## Actual

The tag is clipped to a 1px line

https://github.com/anyboxhq/bug-reports-anybox/assets/4161138/63ef4c90-0dc8-41ed-81dd-98f1eed9447b

## Notes

The issue resolves itself when a) moving the link to a different list or b) force-quit and relaunching the app

**Comment by francisfeng** [comment]
I saw this issue as well. But I can’t reproduce it reliably. 

I came up a solution hoping to fix this in version 2.1.3.

Let me know if you’re still seeing it.

**Comment by michalcs** [comment]
Thanks for looking into this. The issue is no longer reproducible for me in 2.1.4 (210) 

Cheers
