### ISSUE TITLE
`substack.com` articles not parsed correctly in Reader mode

### ISSUE THREAD

**Issue by michalcs** [anyboxhq/bug-reports-anybox#3]
```
macOS Sonoma 14.2 Beta (23C5030f)
Anybox 2.1.2 (176)

iOS 17.1
Anybox 2.1.2 (190)
```

## Steps 

1. From a browser, save a link of any Substack article containing headings, for example [this one](https://ryancraventech.substack.com/p/the-case-against-100-code-coverage)
2. In Anybox, download the article
3. and open the link in Reader mode

## Expected

The article should be parsed with all headings in reading mode

## Actual

The article is missing the headings in reading mode

Original | Safari Reader | Anybox Reader
--- | --- | ---
![CleanShot 2023-11-06 at 15 35 29@2x](https://github.com/anyboxhq/bug-reports-anybox/assets/4161138/b72d930d-468a-4643-accb-2176689b46ad) | ![CleanShot 2023-11-06 at 15 37 11@2x](https://github.com/anyboxhq/bug-reports-anybox/assets/4161138/5fff38e1-22e4-47f6-9232-8b0a135a0152) | ![CleanShot 2023-11-06 at 15 37 33@2x](https://github.com/anyboxhq/bug-reports-anybox/assets/4161138/df1211c4-8539-4f65-a137-8b5c2da1bc23)

## Notes

Occurs on any substack.com article I've come across.

**Comment by francisfeng** [comment]
This is from https://github.com/mozilla/readability.

**Comment by michalcs** [comment]
Hmmm, ok, most of my issues with Anybox are article parser related — I better take my reports directly there then.

Thanks for the info! Cheers
